name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          milanuzelac/github-actions-test
        tags: |
          type=semver,pattern={{version}}
        flavor: |
          latest=false
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub (if pushing to a private registry)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true # Set to false if you only want to build without pushing
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64 # Example for multi-platform build
        cache-from: type=gha,scope=buildx-cache
        cache-to: type=gha,scope=buildx-cache,mode=max
